### ISSUE TITLE
Chaining does not produce result/plot as expected

### ISSUE THREAD

**Issue by knutfrode** [OpenDrift/trajan#154]
Chaining of operations is quite cool:
```
xr.open_dataset('darpa.nc').traj.gridtime('h').sel(time=slice(datetime(2021, 6, 1), datetime(2021, 9, 1))).traj.contained_in(lonmin=-75, lonmax=30, latmin=33, latmax=45).traj.plot()
```

However, the resulting plot is different from using one line per operation.
I.e. the `contained_in` should filter away trajectories east of 33E, but this does not happen with the above oneliner.

![TrajAn_chaining](https://github.com/user-attachments/assets/c67921fa-1456-4ffb-846b-29cae661e563)

**Comment by gauteh** [comment]
Sounds like a caching issue? Is it in the plot or in the dataset?

**Comment by gauteh** [comment]
You can also use "2021-01-01" strings as date input to slice, you don't have to create datetimes. You can also use traj.seltime, then you don't have to grid it before selecting.

**Comment by knutfrode** [comment]
With seltime one still have to do the gridding after selection? But yes, that would mean less data to grid.
However, here I also want data to start at a specific time (midnight at given day), and in the case of seltime before gridding, I would not be guaranteed that starting time would be on that specific desired hour?
