### ISSUE TITLE
gridtime: tries to interpolate non-float variables.

### ISSUE THREAD

**Issue by gauteh** [OpenDrift/trajan#57]
@knutfrode : how to treat non-numeric values? nearest?

current workaround:
```
ds = ds.drop_vars(['Type', 'File', 'Other var'])
ds.traj.gridtime('1h')
```

**Comment by knutfrode** [comment]
Yes, I guess the best.
Integers may loose meaning with linear interpolation, e.g. masks 0, 1, 2, 3

Could in principle be a user option, but perhaps for later if found necessary
