### ISSUE TITLE
Interpolating model fields onto trajectory

### ISSUE THREAD

**Issue by vic1309** [OpenDrift/trajan#59]
Hei,

First of all, many thanks for creating Trajan, it's very helpful! I wonder how one can obtain time series of modeled variables given a trajectory.  Do you have any recommendations for that?

Cheers,

**Comment by gauteh** [comment]
Thanks! Do you want to extract from another dataset (e.g. norkyst) the values of a variable at the time and position of the trajectory?

**Comment by vic1309** [comment]
Precisely, Gaute.

**Comment by knutfrode** [comment]
Hi Mr. Vic1309!

TrajAn does not yet have this functionality, but OpenDrift does have a method `get_variables_along_trajectory`:
https://opendrift.github.io/_modules/opendrift/models/basemodel.html#OpenDriftSimulation.get_variables_along_trajectory

It is not well documented, but its usage is demonstrated here:
https://opendrift.github.io/gallery/example_wind_drift_coefficient_from_trajectory.html

**Comment by gauteh** [comment]
The first step would be to interpolate the trajectory to the time-steps of the model e.g.:

```
ds = ds.traj.gridtime(times=model.sel(time=slice('2023-01-01', '2023-02-01')).time.values) # (untested)
```

ideally you could use something like rio-xarray or pyresample to get the coordinates of the trajectory in the the coordinates of the model, and use xarray to select the points. In practice it does not work so great yet, and it is something that you can do with opendrift readers at the moment. I think we can make it relatively easy to achieve this with trajan by using the `crs` or [transform](https://opendrift.github.io/trajan/autoapi/trajan/traj/index.html#trajan.traj.Traj.transform) methods. If you open e.g. norkyst and manage to get a pyproj.CRS, e.g. through rio-xarray:

```
import xarray as xr
import rioxarray as _

nk = xr.open_dataset('https://thredds.met.no/thredds/dodsC/sea/norkyst800m/1h/aggregate_be')
nk_crs = nk.rio.crs
```

or if it is in-correct or you have to construct it manually, which is often the case:

```
import pyproj

nk_crs = pyproj.crs.CRS.from_proj4('your proj4 string')
```

you can then transform your drifter dataset to the model projection using:

```
ds = ds.traj.transform(nk_crs) # not very well tested
```

and you should be able to use the new `ds.traj.tx` and `ds.traj.ty` coordinates and select out of the model dataset directly.

**Comment by gauteh** [comment]
cf-xarray works better than rio-xarray at getting the CRS:

```
import cf_xarray as _

gm = nk.cf['grid_mapping']
nk_crs = pyproj.CRS.from_cf(gm.attrs)
print(nk_crs)

```

**Comment by gauteh** [comment]
Check out: https://github.com/OpenDrift/trajan/pull/60/files#diff-91998132051a369c30c3c009f3e3700fdb953918f13a54a5824a19c38f85babe

**Comment by gauteh** [comment]
If you need to interpolate the model, and not just get the nearest, take a look at xarray.Dataset.interp , it is very powerful. We use it here: https://github.com/OpenDrift/trajan/blob/main/trajan/traj2d.py#L141 and here: https://github.com/OpenDrift/trajan/blob/main/trajan/traj1d.py#L213
