### ISSUE TITLE
What kind of convention for trajectories with several simultaneous measurements?

### ISSUE THREAD

**Issue by jerabaul29** [OpenDrift/trajan#65]
Following #63 : this may deserve a discussion thread of its own: how to handle different kinds of obs in the same netcdf file to balance between CF conventions and the fact that our need is a bit special?

> Ok. My 2 cents, of course I may be wrong / I am very open to changing my opinion / following your lead on what you want trajan to do :) :
>
>    - having a single obs dim and using it for both gnss, imu, etc, feels a bit weird / inefficient as there will be plenty of NaNs scattered in the gnss, imu, etc, arrays; while these can be compressed, I think this is potentially confusing for the user and may (?) be harder to parse; so I would vote for keeping 1 obs dimension per observed quantity
>    - if having several obs dimensions, it feels like either they all should be "qualified", or none of them should be qualified, so obs_XXX where XXX is the kind of the obs for each of them.
>
> CF conventions are very nice but a bit "narrow" feels like sometimes (which is likely a good thing, having narrow conventions makes for easier parsing etc :) ). Wondering if "extending" the convention about having obs_XXX with XXX the name of the obs for files that contain several kinds of obs that are not sampled simultaneously would be a reasonable and nice extension?

> I agree, it is better to go with option 2: separate obs-dimensions. However, after some discussion, we think it is better to go with just obs for the lat/lon observations. This follows the CF-example, even though it is not perfect. In theory position observations could come from other things than gnss, so if we are to suggest a generic name for position observations for the future CF-convention we should maybe also consider that.
>
> We should also document how we interpret and further narrow / constrict the CF-standard on the trajan documentation site, and eventually suggest to the CF-convention further improvements.

**Comment by gauteh** [comment]
Currently going for different obs dimensions.
