### ISSUE TITLE
```read_csv```: couple of issues

### ISSUE THREAD

**Issue by jerabaul29** [OpenDrift/trajan#67]
I am facing a few issues with ```read_csv```; taking in example the data from the drifters around Svalbard (if you need to reproduce, you should have access to these data @gauteh @knutfrode :) : https://github.com/jerabaul29/DriftersAroundSvalbard-2022/tree/main/Data/SealsCruise_Martin

```
~/Desktop/Current/DriftersAroundSvalbard-2022/Data/SealsCruise_Martin [main|✔]> ipython3
Python 3.8.10 (default, Mar 13 2023, 10:26:41) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from pathlib import Path
   ...: import trajan as ta

In [2]: path_data = Path.cwd().parent.parent / "Data" / "SealsCruise_Martin" / "all_data.csv"

In [3]: seals_data = ta.read_csv(path_data, lon="Lon", lat="Lat", time="Timestamp", name="Instrument")

In [4]: seals_data
Out[4]: 
<xarray.Dataset>
Dimensions:        (trajectory: 5, obs: 2792)
Coordinates:
  * trajectory     (trajectory) int64 0 1 2 3 4
  * obs            (obs) int64 0 1 2 3 4 5 6 ... 2786 2787 2788 2789 2790 2791
Data variables:
    drifter_names  (trajectory) object 'T1' nan nan nan nan
    time           (trajectory, obs) datetime64[ns] 2022-03-21T18:00:08 ... 2...
    lat            (trajectory, obs) float64 72.57 72.57 72.56 ... 68.26 68.26
    lon            (trajectory, obs) float64 -16.95 -16.97 ... -23.61 -23.64
Attributes:
    Conventions:         CF-1.10
    featureType:         trajectory
    geospatial_lat_min:  66.83907
    geospatial_lat_max:  72.87927
    geospatial_lon_min:  -31.53676
    geospatial_lon_max:  -15.77999

In [5]: seals_data.to_netcdf("test.nc")
/home/jrmet/.local/lib/python3.8/site-packages/xarray/coding/times.py:613: RuntimeWarning: invalid value encountered in cast
  int_num = np.asarray(num, dtype=np.int64)
```

Issues I can see (maybe there are some more):

- ```drifter_names  (trajectory) object```: object will not be netcdf dumpable? (would it be possible to have a string, or unicode, or something like this? The omb reader got ```drifter_names                        (trajectory) <U16 'RockBLOCK 206633'...```, which is dumped to netcdf as ```string drifter_names(trajectory) ;``` by ```.to_netcdf```; I think trying to dump xr datasets with objects have given me crashes in the past.

- ```'T1' nan nan nan nan```: not sure why there are nans? Seems like names after T1 are not captured?

- some issue as you can see trying to dump, due to an "invalid cast" with the int64, not sure why?

**Comment by gauteh** [comment]
Yes, it seems like something fishy. We should also ensure the drifter_names is a string. I'll experiment a bit.

**Comment by jerabaul29** [comment]
Yes of course :) .

**Comment by gauteh** [comment]
#68 fixes the first issues, not sure where the casting warning / error comes from. Might be us, or it might be an xarray / netcdf thing.
