### ISSUE TITLE
Skillscore 

### ISSUE THREAD

**Issue by Bente-Moerman** [OpenDrift/trajan#69]
Hei, I have a question about the Liu-Weisberg skillscore calculated with trajan. In attached folder you can find data and script I am using. I did multiple simulations with OpenDrift and I try to let trajan calculate the skillscore for all of them in once by using a for loop. Now for some simulations I got a nice list of scores and for others I got a list full of zeros. Does this has something to do with the tolerance threshold in the calculation of the score? 

[skillscore_problem.zip](https://github.com/OpenDrift/trajan/files/11233278/skillscore_problem.zip)

**Comment by gauteh** [comment]
I am looking at the notebook you sent, which figures are problematic. Do you have an example of one that works, and one that does not? And have you tried plotting the trajectories of those that give zero skill-score?

**Comment by gauteh** [comment]
@Bente-Moerman : There's a distance_to function that will be available after we merge #74 .
