### ISSUE TITLE
no time_coverage_start and time_coverage_end attributes on the csv read?

### ISSUE THREAD

**Issue by jerabaul29** [OpenDrift/trajan#70]
Using the same test case as in https://github.com/OpenDrift/trajan/issues/67 , seeing now that the time_coverage attributes are missing:

```
load SealsCruise_Martin data
<xarray.Dataset>
Dimensions:        (trajectory: 5, obs: 2792)
Coordinates:
  * trajectory     (trajectory) int64 0 1 2 3 4
  * obs            (obs) int64 0 1 2 3 4 5 6 ... 2786 2787 2788 2789 2790 2791
Data variables:
    drifter_names  (trajectory) <U2 'T1' 'T2' 'T3' 'T4' 'T5'
    time           (trajectory, obs) datetime64[ns] 2022-03-21T18:00:08 ... 2...
    lat            (trajectory, obs) float64 72.57 72.57 72.56 ... 68.26 68.26
    lon            (trajectory, obs) float64 -16.95 -16.97 ... -23.61 -23.64
Attributes:
    Conventions:         CF-1.10
    featureType:         trajectory
    geospatial_lat_min:  66.83907
    geospatial_lat_max:  72.87927
    geospatial_lon_min:  -31.53676
    geospatial_lon_max:  -15.77999
```

**Comment by gauteh** [comment]
No, actually the geospatial bounds are also not required by the standard. Should we keep these? Also `drifter_names` should maybe be `trajectory` coordinate.

**Comment by knutfrode** [comment]
time_coverage and geospatial bounds are not required by CF-convention, but are commonly used/parsed by many softwares as "discovery metadata": https://gcw.met.no/node/4
So I would recommend including these automatically, whenever possible.

**Comment by jerabaul29** [comment]
A note: if I remember correctly, when I pushed my data to adc.met.no , they asked me to add these, as they use these to automatically generate som of their metadata on the dataset webpage. This is one example of what @knutfrode says, and if we want to use adc in the future (which is likely), this makes generating these automatically very useful :) .
