### ISSUE TITLE
drifter_names should maybe be named trajectory

### ISSUE THREAD

**Issue by gauteh** [OpenDrift/trajan#71]
http://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html#trajectory-data

drifter_names should probably be trajectory variable. It can then be omitted if there are no names.

@knutfrode, @jerabaul29 : any thoughts?

ref: #70

**Comment by knutfrode** [comment]
Yes, this is good.
As discussed, we should also include the correct attributes:
```
     trajectory:cf_role = "trajectory_id";
     trajectory:long_name = "trajectory name" ;
```
