### ISSUE TITLE
allow different kinds of plots

### ISSUE THREAD

**Issue by jerabaul29** [OpenDrift/trajan#87]
@gauteh one thing I was wondering: as we add more kinds of data in addition to trajectory (e.g., spectra, temperature, salinity, etc), could / should we also provide dedicated plotting methods for these, and if so how?

For example, when wave data / spectra are produced, it is quite convenient to plot the spectrograms and / or Tp and Hs. Do you think we could / should implement ways to plot these easily? Tp and Hs are simple as they are just curves, but for example for spectrograms I have functions that include a bit of logics that would be nice to "factorize".

If this makes sense / is of interest, we can discuss how to make this work best :) .

**Comment by gauteh** [comment]
Hi, yes, I think we should be pragmatic. Waves and trajectories often co-exist. I assume this doesn't work with the standard xarray package? Maybe that is even where it would fit better, but we can have it in trajan until it goes in there. For xarray it would be:

```
ds.hm0.plot()
ds.sel(time=t0).E.plot()
```
