### ISSUE TITLE
provide some "example of use" / "best practice" with slightly more complex xarray commands?

### ISSUE THREAD

**Issue by jerabaul29** [OpenDrift/trajan#88]
Wondering if it could be useful to provide some "example of use" / "recommended best practice" that are not really trajan per se, but maybe more "hidden / not obvious xarray commands". The logics for this is that there are plenty of powerful xarray commands, but they are sometimes a bit finicky to get to work. Would it be useful to have some examples that we could point users to?

For example the following is a few simple but "not obvious for all users" uses of sel, isel, slice, etc; I have seen some users of trajan / xarray write long complex methods by hand because they did not know something like this was possible:

```python
# %%

xr_buoys = xr.open_dataset("./2024_KVS_deployment.nc")

xr_buoys

# %%

# select a specific buoy
xr_specific_buoy = xr_buoys.sel(trajectory="KVS-02")

xr_specific_buoy

# %%

# select several buoys
xr_several_buoys = xr_buoys.sel(trajectory=["KVS-02", "KVS-03"])

xr_several_buoys

# %%

# make a restricted dataset about only the GPS data
xr_specific_buoy_gps = xr_specific_buoy.swap_dims({'obs': 'time'})[["lat", "lon"]]
# keep only the valid GPS points: avoid the NaT that are due to time alignment in the initial nc file
xr_specific_buoy_gps = xr_specific_buoy_gps.dropna(dim='time')

xr_specific_buoy_gps

# %%

# select a specific time; this will select a time "at least as specific as" what is asked, for example 2024-04-12T11:30:38
xr_specific_buoy_gps_timepoint = xr_specific_buoy_gps.sel(time="2024-04-12T11:30")
xr_specific_buoy_gps_timepoint

# %%

# select a time slice; this will select all times between the 2 times chosen
start_time = '2024-04-12T11'
end_time = '2024-04-12T11:40'
xr_specific_buoy_gps_timeslice = xr_specific_buoy_gps.sel(time=slice(start_time, end_time))
xr_specific_buoy_gps_timeslice

# %%

# plot whatever trajectory you want
xr_specific_buoy_gps.sel(time=slice("2024-04-12T11", "2024-04-14T14")).traj.plot()
plt.show()
```

If this is of interest to host on trajan, I could provide some PR illustrating these best practice. Of course this means one more thing to maintain / agreeing on what best practices are, so a bit of work...

**Comment by gauteh** [comment]
Absolutely! I think documenting this in examples is extremely useful and fits the way many users of opendrift / trajan / wave data work.
